# Generated by Django 4.1 on 2024-05-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpricebjse",
            name="ma10",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockpricebjse",
            name="ma20",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockpricebjse",
            name="ma30",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockpricebjse",
            name="ma5",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
