# Generated by Django 4.1 on 2024-05-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_stockpricesse_ma10_stockpricesse_ma20_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpricebjse",
            name="nine_turn_signal_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockpricesse",
            name="nine_turn_signal_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockpriceszse",
            name="nine_turn_signal_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
